name: tack_habit
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: "^4.1.2"
  google_fonts: ^1.1.2
  animated_bottom_navigation_bar: ^0.2.1
  rich_alert: ^0.1.32
  provider: ^4.3.3
  cloud_firestore: ^0.16.0
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  rflutter_alert: ^1.1.0
  shared_preferences: ^0.5.12+4
  flutter_zoom_drawer: ^1.0.4+1
  cupertino_icons: ^0.1.2
  animated_text_kit: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.2.9

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appIcon.png"

flutter_native_splash:
  color: "#545454"
  image: assets/splashIcon.png

flutter:
  uses-material-design: true
